=== bwise-7365/titan-alloy/in_swift/Logistics/rsrcs/srrn.dtd
<!-- 
  This is a basic DTD for specifying valid
  railroad networks in the SWIFT Stalingrad game,
  inspired by the original from Avalon Hill 1963,
  1974, and variants up to 2010.
  Note that a Junction must have at least one RailLine.
 -->

  <!ELEMENT description  (#PCDATA)>
  <!ATTLIST description
    text       	CDATA #REQUIRED>
	
 
  <!ELEMENT name (#PCDATA)>
 
  <!ELEMENT cell (#PCDATA)>
  <!ATTLIST cell
    row       	CDATA #REQUIRED
    clm       	CDATA #REQUIRED>
	 
  
  <!ELEMENT RailRoadNetwork (description?, Arcs, Nodes)>
  
  <!-- These RailLine should each have at least two cells -->
  <!ELEMENT Arcs (RailLine*)>
  
  <!ELEMENT Nodes (Junction*)>

  <!ELEMENT RailLine (cell*)>
  <!ATTLIST RailLine
    name       	CDATA #REQUIRED>

  <!-- These RailLine should have zero cells -->
  <!ELEMENT Junction (cell, RailLine+)>
  <!ATTLIST Junction
    name       	CDATA #REQUIRED>
	
  
<!-- end of DTD -->

=== bwise-7365/titan-alloy/in_swift/Logistics/rsrcs/testRR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE RailRoadNetwork SYSTEM "srrn.dtd">
<RailRoadNetwork>
    <description text="Example file"/>
    <!--
This file is just to test syntax and debug reading.
Syntax is specified in the above DTD,
semantics is checked during reading.
For example, the RailLine specification inside the Junction
must have zero cells.
    -->
    <Arcs>
        <RailLine name="L-10">
            <cell row="26" clm="23"/> <!-- Alpha -->
            <cell row="25" clm="23"/>
            <cell row="24" clm="24"/>
            <cell row="24" clm="25"/>
            <cell row="23" clm="26"/>
            <cell row="23" clm="27"/>
            <cell row="22" clm="28"/>
            <cell row="22" clm="29"/>
            <cell row="22" clm="30"/>
            <cell row="22" clm="31"/>
            <cell row="21" clm="31"/>
            <cell row="20" clm="31"/>
            <cell row="19" clm="32"/> <!-- Moscow -->
        </RailLine>
        <RailLine name="L-11">
            <cell row="26" clm="23"/> <!-- Alpha -->
            <cell row="26" clm="24"/>
            <cell row="27" clm="25"/>
            <cell row="27" clm="26"/>
            <cell row="28" clm="27"/>
            <cell row="29" clm="27"/>
            <cell row="30" clm="27"/>
            <cell row="31" clm="27"/>
            <cell row="32" clm="27"/>
            <cell row="32" clm="28"/>
            <cell row="33" clm="28"/>
            <cell row="34" clm="28"/>
            <cell row="35" clm="28"/> <!-- Kubishev East -->
        </RailLine>
        <RailLine name="L-12">
            <cell row="26" clm="23"/> <!-- Alpha -->
            <cell row="26" clm="22"/>
            <cell row="27" clm="21"/>
            <cell row="27" clm="20"/>
            <cell row="28" clm="19"/>
            <cell row="28" clm="18"/>
            <cell row="29" clm="17"/> <!-- Stalingrad -->
        </RailLine>
        <RailLine name="L-13">
            <cell row="19" clm="23"/> <!-- Kursk -->
            <cell row="20" clm="23"/>
            <cell row="21" clm="23"/>
            <cell row="22" clm="23"/>
            <cell row="23" clm="23"/>
            <cell row="24" clm="23"/>
            <cell row="25" clm="23"/>
            <cell row="26" clm="23"/> <!-- Alpha -->
        </RailLine>
    </Arcs>
    <Nodes>
        <Junction name="Alpha Junction">
            <cell row="26" clm="23"/>
            <RailLine name="L-11"/>
            <RailLine name="L-13"/>
            <RailLine name="L-12"/>
            <RailLine name="L-10"/>
        </Junction>
        <Junction name="Kubishev East Terminal">
            <cell row="35" clm="28"/>
            <RailLine name="L-11"/>
        </Junction>
        <Junction name="Kursk Junction">
            <cell row="19" clm="23"/>
            <RailLine name="L-13"/>
            <RailLine name="L-28"/>
            <RailLine name="L-33"/>
            <RailLine name="L-55"/>
        </Junction>
        <Junction name="Moscow Junction">
            <cell row=" 19 " clm=" 32  "/>
            <RailLine name="L-10"/>
            <RailLine name="L-37"/>
            <RailLine name="L-38"/>
            <RailLine name="L-72"/>
        </Junction>
        <Junction name="Stalingrad Junction">
            <cell row="29" clm="17"/>
            <RailLine name="L-12"/>
            <RailLine name="L-15"/>
            <RailLine name="L-20"/>
        </Junction>
    </Nodes>
</RailRoadNetwork>
