=== bwise-7365/titan-alloy/irrgo/design_resources/ggb.dtd
<!ELEMENT rectangularP (#PCDATA)>
  <!ATTLIST rectangularP
      val       	(True | False )  #REQUIRED>
      
  <!ELEMENT sideToMove (#PCDATA)>
  <!ATTLIST sideToMove
      color       	(Black | White )  #REQUIRED>
      
  <!ELEMENT node (#PCDATA)>
  <!ATTLIST node
      id       	CDATA #REQUIRED>
  
  <!ELEMENT color (#PCDATA)>
  <!ATTLIST color
      val       	(Black | White | Vacant ) #REQUIRED>
  
  <!ELEMENT X (#PCDATA)>
  <!ATTLIST X
      val       	CDATA #REQUIRED>
  
  <!ELEMENT Y (#PCDATA)>
  <!ATTLIST Y
      val       	CDATA #REQUIRED>
  
  <!ELEMENT movenum  (#PCDATA)>
  <!ATTLIST movenum
      num       	CDATA #REQUIRED>
  
  <!ELEMENT edge (node, node)>
  <!ELEMENT edge_list (edge*)>
  <!ELEMENT coord (node, X, Y)>
  <!ELEMENT coord_list (coord*)>
  <!ELEMENT stone (node, color)>
  <!ELEMENT Position (stone*)>
  <!ELEMENT move (node, color, movenum)>
  <!ELEMENT move_list (move*)>
  <!ELEMENT GraphGoBoard (rectangularP, coord_list, edge_list, Game)>
  <!ELEMENT Game (sideToMove, Position, move_list, Position)>

=== bwise-7365/titan-alloy/irrgo/design_resources/ggb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GraphGoBoard SYSTEM "ggb.dtd">
<GraphGoBoard>
	<rectangularP val="False"/>
	<coord_list>
		<coord>
			<node id="0"/>
			<X val="865"/>
			<Y val="654"/>
		</coord>
		<coord>
			<node id="1"/>
			<X val="258"/>
			<Y val="897"/>
		</coord>
		<coord>
			<node id="2"/>
			<X val="488"/>
			<Y val="98"/>
		</coord>
		<coord>
			<node id="3"/>
			<X val="856"/>
			<Y val="273"/>
		</coord>
	</coord_list>
	<edge_list>
		<edge>
			<node id="9"/>
			<node id="27"/>
		</edge>
		<edge>
			<node id="6"/>
			<node id="47"/>
		</edge>
		<edge>
			<node id="6"/>
			<node id="37"/>
		</edge>
		<edge>
			<node id="11"/>
			<node id="29"/>
		</edge>
	</edge_list>
	<Game>
		<sideToMove color="Black"/>
		<Position>
			<stone>
				<node id="0"/>
				<color val="Black"/>
			</stone>
			<stone>
				<node id="4"/>
				<color val="White"/>
			</stone>
			<stone>
				<node id="5"/>
				<color val="Black"/>
			</stone>
		</Position>
		<move_list>
			<move>
				<node id="8"/>
				<color val="Black"/>
				<movenum num="2"/>
			</move>
			<move>
				<node id="7"/>
				<color val="White"/>
				<movenum num="1"/>
			</move>
			<move>
				<node id="39"/>
				<color val="Black"/>
				<movenum num="0"/>
			</move>
		</move_list>
		<Position>
    </Position>
	</Game>
</GraphGoBoard>
